---
- name: Basic URI playbook
  hosts: "{{ target | default('all') }}"
  gather_facts: false
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:

  - name: Request URL
    ansible.builtin.uri:
      url: "{{ survey_url }}"
      return_content: true
    register: result

  - name: Show URL content
    ansible.builtin.debug:
      msg: "{{ result }}"
